### ISSUE TITLE
Fix N^2 NDTW core algorithm

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/NaluWindUtils#1]
It looks like to me that the NDTW algorithm is N*N. If we plan on running larger cases, we should consider the following reference/implementation:

https://pdfs.semanticscholar.org/f6da/23490796728014aef24d497724e8329c002c.pdf

This would introduce upper and lower bounds to reduce communication. 

Obstructions are another complication that we may not require to resolve.

**Comment by sayerhs** [comment]
@spdomin: This was a temporary hack for Ganesh and as you can see in the NDTW2D documentation/TODO, this was going to be deprecated when moving to percept.

**Comment by spdomin** [comment]
@sayerhs. Right. I think that for the short term, this is fine. If I end up with a half day free, I can make the full set of changes noted in the above paper. However, as we discussed, the best path may be to wait for the SNL open-sourced "Krini" code base.
