### ISSUE TITLE
Question about multiblock mesh generation

### ISSUE THREAD

**Issue by yoonc5536** [NaluCFD/NaluWindUtils#10]
Hello, I'm considering a multi-block mesh for Nalu-Wind. abl_mesh seems to only support the single block mesh generation using the YAML input. If I use the function, convert_plot3d, do you think I can generate the multiblock exodus mesh converting multi-block Plot3D mesh?

**Comment by sayerhs** [comment]
@yoonc5536 the plot 3D Interface in wind-utils will have to be modified to support multiple blocks, but it should be a fairly straightforward update. The current version doesn't do multiple blocks
